import {
  SET_DIALOG_STATUS,
  LOAD_PRODUCT_REQUEST,
  LOAD_PRODUCT_FAILURE,
  LOAD_PRODUCT_SUCCESS,
  LOAD_DETAIL_FAILURE, LOAD_DETAIL_REQUEST
, LOAD_DETAIL_SUCCESS,
LOAD_PRODUCT_DETAIL_FAILURE,
LOAD_PRODUCT_DETAIL_REQUEST,
LOAD_PRODUCT_DETAIL_SUCCESS,
LOAD_HISTORY_DETAIL_FAILURE,
LOAD_HISTORY_DETAIL_REQUEST,
LOAD_HISTORY_DETAIL_SUCCESS,
RETURN_PRODUCT_REQUEST,
RETURN_PRODUCT_FAILURE,
RETURN_PRODUCT_SUCCESS,
LOAD_PRODUCT_IMPORT_REQUEST,
LOAD_PRODUCT_IMPORT_FAILURE,
LOAD_PRODUCT_IMPORT_SUCCESS,
GET_REPORT_REQUEST,
GET_REPORT_FAILURE,
GET_REPORT_SUCCESS,
LOAD_BILL_DETAIL_REQUEST,
LOAD_BILL_DETAIL_FAILURE,
LOAD_BILL_DETAIL_SUCCESS,
ADD_STORE_REQUEST,
LOAD_STORE_REQUEST,
UPDATE_STORE_REQUEST,
ADD_STORE_FAILURE,
LOAD_STORE_FAILURE,
UPDATE_STORE_FAILURE,
LOAD_STORE_SUCCESS,
ADD_STORE_SUCCESS,
 UPDATE_STORE_SUCCESS,
 LOAD_HISTORY_REQUEST,
 LOAD_HISTORY_SUCCESS,
 LOAD_HISTORY_FAILURE,
  IMPORT_PRODUCT_FAILURE,
   IMPORT_PRODUCT_REQUEST, IMPORT_PRODUCT_SUCCESS, LOAD_STORE_INFO_REQUEST, LOAD_STORE_INFO_FAILURE, LOAD_STORE_INFO_SUCCESS,
   SET_LOADING,
   GET_CUSTOMER_FAILURE, GET_CUSTOMER_REQUEST, GET_CUSTOMER_SUCCESS

} from '../actions';

const INITIAL_STATE = {
  showDialog: false,
  dialogType: '',
  loading: false
};

export default (state = INITIAL_STATE, action) => {
  switch (action.type) {
    case SET_DIALOG_STATUS:
      return {
        showDialog: action.payload.showDialog,
        dialogType: action.payload.dialogType
      };
      case ADD_STORE_SUCCESS:
      case LOAD_PRODUCT_FAILURE:
      case LOAD_PRODUCT_SUCCESS:
      case LOAD_DETAIL_FAILURE:
     case LOAD_DETAIL_SUCCESS:
     case LOAD_PRODUCT_DETAIL_FAILURE:
     case LOAD_PRODUCT_DETAIL_SUCCESS:
     case LOAD_HISTORY_DETAIL_FAILURE:
     case LOAD_HISTORY_DETAIL_SUCCESS:
     case RETURN_PRODUCT_FAILURE:
     case RETURN_PRODUCT_SUCCESS:
     case LOAD_PRODUCT_IMPORT_FAILURE:
     case LOAD_PRODUCT_IMPORT_SUCCESS:
     case GET_REPORT_FAILURE:
     case GET_REPORT_SUCCESS:
     case LOAD_BILL_DETAIL_FAILURE:
     case LOAD_BILL_DETAIL_SUCCESS:
     case ADD_STORE_FAILURE:
     case LOAD_STORE_FAILURE:
     case UPDATE_STORE_FAILURE:
     case LOAD_STORE_SUCCESS:
     case UPDATE_STORE_SUCCESS:
     case LOAD_HISTORY_SUCCESS:
     case LOAD_HISTORY_FAILURE:
     case IMPORT_PRODUCT_FAILURE:
     case IMPORT_PRODUCT_SUCCESS:
     case LOAD_STORE_INFO_FAILURE:
     case LOAD_STORE_INFO_SUCCESS:
     case GET_CUSTOMER_FAILURE:
     case GET_CUSTOMER_SUCCESS:
       return {
         ...state,
         loading: false
       };
      case LOAD_PRODUCT_REQUEST:
      case LOAD_DETAIL_REQUEST:
      case LOAD_PRODUCT_DETAIL_REQUEST:
      case LOAD_HISTORY_DETAIL_REQUEST:
      case RETURN_PRODUCT_REQUEST:
      case LOAD_PRODUCT_IMPORT_REQUEST:
      case GET_REPORT_REQUEST:
      case LOAD_BILL_DETAIL_REQUEST:
      case ADD_STORE_REQUEST:
      case LOAD_STORE_REQUEST:
      case UPDATE_STORE_REQUEST:
      case LOAD_HISTORY_REQUEST:
      case IMPORT_PRODUCT_REQUEST:
      case LOAD_STORE_INFO_REQUEST:
      case GET_CUSTOMER_REQUEST:
        return {
          ...state,
          loading: true
        };
      case SET_LOADING: return {
        ...state,
        loading: action.payload
      };
    default:
      return { ...state };
  }
};
